Fix build errors caused by updates to github.com/miekg/dns
Errors were (fixes preceded by -):
- 235e892 - Rename the RR types drop the RR_ prefix (6 months ago) [Miek
Gieben]
./main.go:93: undefined: dns.RR_OPT
- Signature of method was changed to accept []byte and new method
  "WriteMsg" was introduced
./main.go:97: cannot use m (type *dns.Msg) as type []byte in function
argument
- Same
./main.go:120: cannot use cached (type *dns.Msg) as type []byte in
function argument
- Method name changed to Exchange
./main.go:126: c.ExchangeRtt undefined (type *dns.Client has no field or
method ExchangeRtt)